version: '3.8'

services:
  backend-flask:
    build: ./backend-flask
    container_name: nutribot-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5000
      - CORS_ORIGINS=http://localhost:3000,http://your-vm-ip:3000
    env_file:
      - ./backend-flask/.env
    restart: always

  nutribot-next:
    build: ./nutribot-next
    container_name: nutribot-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://your-vm-ip:5000
    depends_on:
      - backend-flask
    restart: always
